<a href="https://colab.research.google.com/github/Jrodos12/Organizacion-de-Datos/blob/main/Analisis%20exploratorio%20de%20datos/Pandas_Ejer_38_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Obtenga la matriz de correlación para saber idiomas distintos considerando que un usuario sabe un idioma si indicó un nivel de 1 o superior (⭐⭐)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
dataframeLenguajes = pd.read_csv("drive/MyDrive/languages.csv")
#cambio los nombre para mas comodidad
dataframeLenguajes = dataframeLenguajes.rename(columns= {"babel_user":"usuario", "babel_lang" : "idioma","babel_level": "nivel_idioma"})
#chequeo la existencia de Nan
dataframeLenguajes.isnull().sum()

usuario         0
idioma          4
nivel_idioma    0
dtype: int64

observo 2 situaciones usuarios con nivel 0 de un idioma, es decir que no sabe el idioma y usuarios con nivel N (nativos) es decir saben el idioma.
Asi mismo observo que 1,2,3,4,5 son equivalentes a saber el idioma

In [ ]:
dataframeLenguajes["nivel_idioma"].unique()

array(['2', '0', '1', '3', '4', 'N', '5'], dtype=object)

In [ ]:
dataframeLenguajes["sabe_idioma"] = dataframeLenguajes["nivel_idioma"].map(lambda x: 0 if x == "0" else 1)

In [ ]:
dataframeLenguajes["sabe_idioma"].unique()

array([1, 0])

In [ ]:
(dataframeLenguajes["idioma"].isna()).sum()

4

existen idiomas con nans, tomo la decision de tratar dichos nans como lenguajes "otros"

In [ ]:
dataframeLenguajes["idioma"].fillna("otros", inplace=True)

In [ ]:
(dataframeLenguajes["usuario"].isna()).sum()

0

In [ ]:
lenguajes_pivot = dataframeLenguajes.pivot("usuario","idioma","sabe_idioma")

<ipython-input-9-c2116be6426d>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.pivot will be keyword-only.
  lenguajes_pivot = dataframeLenguajes.pivot("usuario","idioma","sabe_idioma")

In [ ]:
lenguajes_pivot.fillna(0, inplace=True)

In [ ]:
lenguajes_pivot

idioma,FR,aa,ab,ace,acf,af,agr,akk,aln,alt,...,zap,zea,zh,zh-Hans,zh-Hans-CN,zh-Hant,zh-Hant-HK,zh-Hant-TW,zu,zza
usuario,,,,,,,,,,,,,,,,,,,,,
30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
262,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
267,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6318249,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6327193,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6327824,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6331490,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6332447,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#preguntarle a gian, a que se refiere con los numeros
lenguajes_pivot.corr()

idioma,FR,aa,ab,ace,acf,af,agr,akk,aln,alt,...,zap,zea,zh,zh-Hans,zh-Hans-CN,zh-Hant,zh-Hant-HK,zh-Hant-TW,zu,zza
idioma,,,,,,,,,,,,,,,,,,,,,
FR,1.000000,NaN,-0.000092,NaN,-0.000092,-0.000293,-0.000092,-0.000092,-0.000131,NaN,...,-0.000092,-0.000092,-0.001289,-0.000092,-0.000160,-0.000092,-0.000092,-0.000092,NaN,-0.000092
aa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ab,-0.000092,NaN,1.000000,NaN,-0.000092,-0.000293,-0.000092,-0.000092,-0.000131,NaN,...,-0.000092,-0.000092,-0.001289,-0.000092,-0.000160,-0.000092,-0.000092,-0.000092,NaN,-0.000092
ace,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
acf,-0.000092,NaN,-0.000092,NaN,1.000000,-0.000293,-0.000092,-0.000092,-0.000131,NaN,...,-0.000092,-0.000092,-0.001289,-0.000092,-0.000160,-0.000092,-0.000092,-0.000092,NaN,-0.000092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zh-Hant,-0.000092,NaN,-0.000092,NaN,-0.000092,-0.000293,-0.000092,-0.000092,-0.000131,NaN,...,-0.000092,-0.000092,0.071719,1.000000,0.577297,1.000000,1.000000,1.000000,NaN,-0.000092
zh-Hant-HK,-0.000092,NaN,-0.000092,NaN,-0.000092,-0.000293,-0.000092,-0.000092,-0.000131,NaN,...,-0.000092,-0.000092,0.071719,1.000000,0.577297,1.000000,1.000000,1.000000,NaN,-0.000092
zh-Hant-TW,-0.000092,NaN,-0.000092,NaN,-0.000092,-0.000293,-0.000092,-0.000092,-0.000131,NaN,...,-0.000092,-0.000092,0.071719,1.000000,0.577297,1.000000,1.000000,1.000000,NaN,-0.000092
zu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zza,-0.000092,NaN,-0.000092,NaN,-0.000092,-0.000293,-0.000092,-0.000092,-0.000131,NaN,...,-0.000092,-0.000092,-0.001289,-0.000092,-0.000160,-0.000092,-0.000092,-0.000092,NaN,1.000000